config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#index"
  resources :users, only: [:index, :show]
  resources :tasks, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ActiveHash::Base
  self.data = [
    { id: 1, name: '0' },
    { id: 2, name: '1' },
    { id: 3, name: '2' },
    { id: 4, name: '3' },
    { id: 5, name: '4' },
    { id: 6, name: '5' },
    { id: 7, name: '6' },
    { id: 8, name: '7' },
    { id: 9, name: '8' },
    { id: 10, name: '9' },
    { id: 11, name: '10' }
  ]

  include ActiveHash::Associations
  has_many :tasks
end  

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :score

  validates :content, presence: true
  validates :content, uniqueness: { scope: :content , message: "はすでにあります" }
  validates :content, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "は全角で入力してください" }

end

app/models/user.rb
class User < ApplicationRecord

  has_many :tasks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, length: { maximum: 10 }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角英数字で入力してください" }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
  end
  
  def new
    @task = Task.new
  end  

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end  
  end  

  private

    def task_params
      params.require(:task).permit(:content, :score_id).merge(user_id: current_user.id)
    end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all 
  end  

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
    
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kohoubi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="error-alert", id="error_explanation" data-turbo-cache="false">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages2.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_user_go.html.erb
<%= link_to "さいしょにもどる", root_path %><br />

app/views/tasks/new.html.erb
<div class="kohoubi-header">
  <div class="header-logo">~やることをきめる！~</div>
</div>

<%= form_with model: @task, local: true do |f| %>
  <%= render 'shared/error_messages2', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">やること</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :content, class:"input-default", id:"content", placeholder:"やることをかいてね" %>
  </div>

  <div class='register-btn'>
    <%= f.submit "とうろく！" ,class:"register-red-btn" %>
  </div>
<% end %>

<%= render "shared/user_go" %>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="kohoubi-header">
    <div class="header-logo">こほうび</div>
    <ul class='user-menu'>
      <% if user_signed_in? %>
        <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "user-menu-btn" %></li> 
        <li><%= link_to 'やることをきめる', new_task_path, class: "user-menu-btn" %></li>
      <% else %>  
        <li><%= link_to 'ログイン', new_user_session_path, class: "user-menu-btn" %></li>
        <li><%= link_to 'しんきとうろく', new_user_registration_path, class: "user-menu-btn" %></li>
      <% end %> 
    </ul>
  </div>  
  <div class="users-index-contents">
    <div class="users-index-title">ユーザー一覧</div>
    <div class="users-index-item">
    <% @users.each do |user| %>
      <div class="user-index-list">
        <%= link_to user.nickname, user_path(user), class: "user-index-name" %>
      </div>  
    <% end %>
    </div>
  </div>  
</div>

app/views/users/show.html.erb
<div class="main users-index">
  <div class="kohoubi-header">
    <div class="header-logo">ユーザーのじょうほう</div>
    <ul class='user-menu'>
      <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "user-menu-btn" %></li> 
      <li><%= link_to 'やることをきめる', new_task_path, class: "user-menu-btn" %></li>
    </ul>
  </div>  
  <div class="users-index-contents">
    <div class="users-index-item">
      <div class="user-list">
        <h2 class="name">
          <%= @user.nickname %>
        </h2>
        <div class="user-list-content">
          <div class="user-task-list">
            <div class="user-list-task-title">
              <div class="user-list-task-titlelog">やること</div>
              <div class="user-list-task-titlelog">得点</div>
            </div>
            <ul class="user-daily-tasks">
              <% @tasks.each do |task| %> 
              <li class="user-daily-task">
                <%= task.content %> 
              </li>
              <% end %>   
            </ul>
          </div>
          <div class="user-reward-list">
            <div class="user-list-reward-title">
              <div class="user-list-reward-titlelog">こほうび</div>
              <div class="user-list-reward-titlelog">点数</div>
            </div>
            <ul class="user-weekly-rewards">
              <li class="user-weekly-reward"></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>  
</div>

<%= render "shared/user_go" %>